PROG=cao-test
MPICXX=mpicxx
MPIEXT = ../mpiext

CFLAGS=-g -c -I$(MPIEXT) -Wall -Wextra -O3 -ffast-math -funroll-loops
LDFLAGS=
SRCS=ECData.cpp  find_neighbors.cpp  kmer_count.cpp  test_main.cpp  Parser.cpp  sort_kmers.cpp caware_layout.cpp  coblivious_layout.cpp util.cpp ErrorCorrector.cpp
OBJS=$(SRCS:.cpp=.o)

ifeq ($(MAKECMDGOALS),debug)
CFLAGS += -g -DDEBUG
endif

ifeq ($(MAKECMDGOALS),counts)
CFLAGS += -g -DQUERY_COUNTS
endif

all:$(SRCS) $(PROG)

$(PROG): $(OBJS)
	$(MPICXX) -o $@ $(OBJS) $(LDFLAGS)

$(OBJS): %.o : %.cpp
	$(MPICXX) $(CFLAGS) $<


clean:
	rm -rf $(PROG) $(OBJS)

debug: all

counts: all
